In [1]:
#Loading Dataset for Country Dataset
library(tidyverse)
CO2 = read.csv('shared_documents/FFG_Hackathon_Country_Level_Data.csv')
head(CO2)

Registered S3 methods overwritten by 'ggplot2':
  method         from
  [.quosures     rlang
  c.quosures     rlang
  print.quosures rlang
Registered S3 method overwritten by 'rvest':
  method            from
  read_xml.response xml2
── Attaching packages ─────────────────────────────────────── tidyverse 1.2.1 ──
✔ ggplot2 3.1.1       ✔ purrr   0.3.2
✔ tibble  2.1.1       ✔ dplyr   0.8.0.1
✔ tidyr   0.8.3       ✔ stringr 1.4.0
✔ readr   1.3.1       ✔ forcats 0.4.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

  Year Country.Name Country.Code AG.LND.AGRI.K2 AG.LND.TOTL.K2 AG.SRF.TOTL.K2
1 2007 Albania      ALB            11190.0        27400          28750
2 2007 Algeria      DZA           412520.0      2381740        2381740
3 2007 Angola       AGO           508468.2      1246700        1246700
4 2007 Argentina    ARG          1440330.0      2736690        2780400
5 2007 Armenia      ARM            17519.0        28470          29740
6 2007 Australia    AUS          3983555.0      7682300        7741220
  EG.ELC.COAL.ZS EG.ELC.FOSL.ZS EG.ELC.HYRO.ZS EG.ELC.NGAS.ZS ...
1  0.000000       2.517483      97.4825175      0.00000       ...
2  0.000000      99.392408       0.6075922     97.25777       ...
3  0.000000      22.381100      77.6188996      0.00000       ...
4  2.179398      63.438998      28.2707257     51.04687       ...
5  0.000000      25.245846      31.4174296     25.24585       ...
6 77.053573      91.351928       5.9013330     13.10772       ...
  EN.ATM.CO2E.SF.ZS EN.CO2.BLDG.ZS EN.CO2.ETOT.ZS EN.CO2.MANF.ZS EN.CO2.OTHX.ZS
1  1.8674136         7.407407       8.730159      16.93122       11.6402116
2  2.7551533        16.028285      40.011786      11.45551        0.0000000
3  0.0000000        23.858921      12.344398      23.54772        0.3112033
4  2.0912269        14.616174      33.816513      20.51096        5.4055686
5  0.1450326        22.291667      22.500000      24.37500        8.7500000
6 55.7366709         3.050716      62.684217      11.16789        1.5305201
  EN.CO2.TRAN.ZS EN.POP.DNST NY.GDP.TOTL.RT.ZS SP.RUR.TOTL SP.URB.TOTL
1 55.55556       108.394781   1.761086092       1517619     1452398
2 32.51621        14.345383  32.464933690      11839539    22327433
3 40.04149        16.768559  46.279011930       8879762    12025601
4 25.64474        14.500837   4.995812922       3823185    35861110
5 22.08333       103.007306   0.009295978       1063397     1869221
6 21.56665         2.711115   6.508260772       3161213    17666387

In [3]:
#Filtering columns out by the country name and year to find the amount of carbon emissions that existed in the timeframe
Carbon_Ozone = CO2 %>% group_by(Country.Name, Year) %>% summarise(Frequency = sum(EN.CO2.ETOT.ZS,na.rm=TRUE))
Carbon_Ozone

     Country.Name Year Frequency
1    Albania      2007  8.730159
2    Albania      2008  7.547170
3    Albania      2009  3.713528
4    Albania      2010  2.544529
5    Albania      2011  2.898551
6    Albania      2012  2.873563
7    Albania      2013  1.373626
8    Albania      2014  2.912621
9    Albania      2015  0.000000
10   Albania      2016  0.000000
11   Algeria      2007 40.011786
12   Algeria      2008 40.034052
13   Algeria      2009 38.830632
14   Algeria      2010 37.924193
15   Algeria      2011 38.869846
16   Algeria      2012 39.866269
17   Algeria      2013 38.426414
18   Algeria      2014 38.826975
19   Algeria      2015  0.000000
20   Algeria      2016  0.000000
21   Angola       2007 12.344398
22   Angola       2008 13.378493
23   Angola       2009 17.808219
24   Angola       2010 17.184402
25   Angola       2011 14.863184
26   Angola       2012 12.586099
27   Angola       2013 14.380531
28   Angola       2014 19.170984
29   Angola       2015  0.000000
30   Angola       2016  0.000000
...  ...          ...  ...
1281 Yemen, Rep.  2007 32.650000
1282 Yemen, Rep.  2008 31.858824
1283 Yemen, Rep.  2009 33.162830
1284 Yemen, Rep.  2010 36.164506
1285 Yemen, Rep.  2011 35.015609
1286 Yemen, Rep.  2012 38.289323
1287 Yemen, Rep.  2013 31.993300
1288 Yemen, Rep.  2014 31.490159
1289 Yemen, Rep.  2015  0.000000
1290 Yemen, Rep.  2016  0.000000
1291 Zambia       2007  3.007519
1292 Zambia       2008  3.973510
1293 Zambia       2009  3.184713
1294 Zambia       2010  4.268293
1295 Zambia       2011  3.030303
1296 Zambia       2012  2.573529
1297 Zambia       2013  2.456140
1298 Zambia       2014  9.717868
1299 Zambia       2015  0.000000
1300 Zambia       2016  0.000000
1301 Zimbabwe     2007 35.343035
1302 Zimbabwe     2008 36.375839
1303 Zimbabwe     2009 38.440111
1304 Zimbabwe     2010 52.979415
1305 Zimbabwe     2011 54.290876
1306 Zimbabwe     2012 49.125874
1307 Zimbabwe     2013 57.653061
1308 Zimbabwe     2014 59.442994
1309 Zimbabwe     2015  0.000000
1310 Zimbabwe     2016  0.000000

In [4]:
#Wrote this into a CSV file as a summary table for more analysis
write.csv(Carbon_Ozone, file = "Total_Carbon_Emissions_By_Country.csv", row.names = FALSE)